# Generated by Django 4.2.30 on 2026-08-19 01:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livepost',
            old_name='post_id',
            new_name='transaction_id',
        ),
        migrations.AddField(
            model_name='livepost',
            name='waktu_penarikan',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
