# Generated by Django 4.2.30 on 2026-08-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_post_id_livepost_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livepost',
            name='transaction_id',
        ),
        migrations.AlterField(
            model_name='livepost',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
