# Generated by Django 4.2.30 on 2026-08-19 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_livepost_transaction_id_alter_livepost_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livepost',
            name='waktu_penarikan',
        ),
    ]
