# Generated by Django 4.2.30 on 2026-08-19 02:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_livepost_waktu_penarikan'),
    ]

    operations = [
        migrations.AddField(
            model_name='livepost',
            name='waktu_penarikan',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
