services:
  postgres:
    image: postgres:18
    container_name: snj-dwh-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: datawarehouse
    ports:
      - "5432:5432"
    volumes:
      - snj_pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: snj-dwh-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres

  airflow-init:
    image: apache/airflow:2.7.1
    container_name: snj-dwh-airflow-init
    depends_on:
      postgres:
        condition: service_healthy
    environment: &airflow-common-env
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:adminpassword@postgres:5432/datawarehouse
      _PIP_ADDITIONAL_REQUIREMENTS: "requests psycopg2-binary"
    volumes:
      - ./dags:/opt/airflow/dags
    command:
      - bash
      - -c
      - |
        airflow db migrate &&
        airflow users create --username admin --password admin --firstname Ridho --lastname Admin --role Admin --email admin@example.com

  airflow-webserver:
    image: apache/airflow:2.7.1
    container_name: snj-dwh-airflow-web
    restart: unless-stopped
    environment: *airflow-common-env
    ports:
      - "8082:8080"
    volumes:
      - ./dags:/opt/airflow/dags
    command: webserver
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    image: apache/airflow:2.7.1
    container_name: snj-dwh-airflow-scheduler
    restart: unless-stopped
    environment: *airflow-common-env
    volumes:
      - ./dags:/opt/airflow/dags
    command: scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully

volumes:
  snj_pgdata: